#!/bin/bash
#PBS -P RMVPE_Training
#PBS -j oe
#PBS -N RMVPE_Training
#PBS -q volta_gpu
#PBS -l select=1:ncpus=6:mem=60gb:ngpus=1
#PBS -l walltime=24:00:00
cd $PBS_O_WORKDIR
np=$(cat ${PBS_NODEFILE} | wc -l)
source /etc/profile.d/rec_modules.sh

image="/app1/common/singularity-img/3.0.0/pytorch_1.11_cuda_11.3_cudnn8-py38.sif"

singularity exec $image bash << EOF > stdout.$PBS_JOBID 2> stderr.$PBS_JOBID
pip list
EOF

# python train.py $HOME/mir1k/MIR-1K